site_name: Sample-Mkdocs
# site_url: 
site_description: sample for mkdocs 
site_author: ryo4432

repo_url: https://github.com/ryo4432/sample-mkdocs/
edit_uri: ""

theme:
    name: material
    feature:
      tabs: true
    language: ja
    highlightjs: true
    hljs_languages:
        - yaml
        - django
    font:
        text: 'Roboto'
        code: 'Roboto Mono'

nav:
    - Home: index.md
    - インストール: 01_install.md
    - 使い方: 02_howtouse.md
    - 基本的な機能: 03_basic_features.md
    - その他の機能: 04_extra_features.md

extra_css:
    - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
    - https://unpkg.com/mermaid@8.0.0/dist/mermaid.css

extra_javascript: 
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - https://unpkg.com/mermaid@8.0.0/dist/mermaid.min.js

markdown_extensions:
    - toc:
        permalink: true
        slugify: !!python/name:pymdownx.slugs.uslugify
    - smarty:
        smart_quotes: false
    - admonition
    - footnotes
    - codehilite:
        linenums: true
    - def_list
#     - markdown.extensions.attr_list:
#     - markdown.extensions.def_list:
#     - markdown.extensions.tables:
#     - markdown.extensions.abbr:
#     - markdown.extensions.md_in_html:
    - mdx_math # 数式
    - pymdownx.tasklist: # チェックボックス
        custom_checkbox: true
    - plantuml_markdown: # plantuml
        server: http://www.plantuml.com/plantuml
    - markdown_inline_graphviz # graphviz
    # ここからpymdownx
    - pymdownx.emoji
    - pymdownx.tabbed
    - pymdownx.tilde
    - pymdownx.superfences:
        preserve_tabs: true
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
          - name: math
            class: arithmatex
            format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
    - pymdownx.magiclink:
        repo_url_shortener: false
        repo_url_shorthand: false
        social_url_shorthand: false
        social_url_shortener: false
    - pymdownx.tilde:
    - pymdownx.caret:
    - pymdownx.betterem:
    - pymdownx.smartsymbols:
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.escapeall:
        hardbreak: True
        nbsp: True
    - pymdownx.mark:
    - pymdownx.keys:
        separator: "\uff0b"
    - pymdownx.tabbed:
    - pymdownx.snippets:
        base_path: docs/
    - pymdownx.details:

copyright: Copyright &copy; 2020 ryo4432

extra:
    search:
      language: 'jp'

plugins:
    - search